import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import { ArtworkProvider } from '../context/ArtworkContext'
import { WalletProvider } from '../context/WalletContext'

const inter = Inter({ subsets: ['latin'], display: 'swap' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <WalletProvider>
      <ArtworkProvider>
        <html lang="en">
          <body className={inter.className}>{children}</body>
        </html>
      </ArtworkProvider>
    </WalletProvider>
  )
}
